# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------
import os
from sphinx_revealjs.themes import get_theme_path

# -- Project information -----------------------------------------------------

project = 'Desarrollo de Aplicaciones en Internet'
copyright = '2022-2023, Juan Antonio Pérez'
author = 'Juan Antonio Pérez'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx_revealjs',
]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'es'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# -- Options for Reveal.js output ---------------------------------------------

revealjs_static_path = ["_static"]
revealjs_style_theme = "black"  # black # white # moon
revealjs_script_conf = {
    "controls": True,
    "progress": True,
    "center": True,
    "transition": "slide",
}
revealjs_css_files = [
    "custom_revealjs.css",
]
reveal_js_files = []
revealjs_notes_from_comments = True
